services:
  vault:
    build: ./vault/
    image: vault2
    container_name: vault2
    ports:
      - "8200:8200"
      - "8300:8300"
    restart: unless-stopped  
    environment:
      VAULT_ADDR: "http://localhost:8300"
    volumes:
      - ./vault/vault-data:/vault/file
    cap_add:
      - IPC_LOCK
    networks:
      - app-network

  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    depends_on: 
      - backend
    networks:
      - app-network

  backend:
    build: ./backend/
    container_name: backend
    volumes:
      - db:/app/src/prisma
      - avatars:/app/public/avatars
    restart: always
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - DEFAULT_AVATAR
      - HTTPS_CERT
      - HTTPS_KEY
      - JWT_EXPIRES_IN
    depends_on:
      - vault
    networks:
      - app-network

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/certs:/etc/nginx/certs
    env_file:
      - .env
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db:
  avatars:
  vault-volume: