services:
  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    depends_on: 
      - backend
    networks:
        - app-network

  backend:
    build: ./backend/
    container_name: backend
    volumes:
      - db:/app/src/prisma
      - avatars:/app/public/avatars
    restart: always
    env_file:
      - ./backend/.env
    networks:
        - app-network


  nginx:

    build: 
      context: .
      dockerfile: nginx/Dockerfile

    container_name: nginx
    
    ports:
      - 443:443
      - 80:80


    depends_on:
      - frontend
      - backend

    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/certs:/etc/nginx/certs

    env_file:
      - .env
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  db:
  avatars: