services:

  frontend:
    build: ./Dockerfiles/frontend/
    container_name: frontend
    restart: always
    depends_on: 
      - backend

    networks:
        - app-network

    expose:
      - 80

  backend:
    build: ./Dockerfiles/backend/
    container_name: backend
    restart: always

    expose: 
      - 3000

    networks:
        - app-network


  nginx:

    build: ./Dockerfiles/nginx/

    container_name: reverse_proxy
    
    ports:
      - 443:443
      - 80:80


    depends_on:
      - frontend
      - backend

    volumes:
        - ./Dockerfiles/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./Dockerfiles/nginx/certs:/etc/nginx/certs

    networks:
      - app-network



networks:
  app-network:
    driver: bridge