services:

  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    depends_on: 
      - backend

    networks:
        - app-network

    expose:
      - 80

  backend:
    build: ./backend/
    container_name: backend
    restart: always

    expose: 
      - 3000
    env_file:
      - ./backend/src/.env
    networks:
        - app-network


  nginx:

    build: ./nginx/

    container_name: nginx
    
    ports:
      - 443:443
      - 80:80


    depends_on:
      - frontend
      - backend

    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/certs:/etc/nginx/certs

    env_file:
      - .env
    networks:
      - app-network



networks:
  app-network:
    driver: bridge